<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Modules\Catalog\Models\Brand;
use App\Modules\Catalog\Models\Category;
use App\Modules\Catalog\Models\HsnCode;
use App\Modules\Catalog\Models\Product;
use App\Modules\Catalog\Models\TaxRate;
use App\Modules\Catalog\Models\UnitOfMeasure;
use App\Modules\Catalog\Models\Warehouse;
use App\Modules\Inventory\Models\Supplier;
use App\Services\InventoryService;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductCatalogSeeder extends Seeder
{
    public function run(): void
    {
        // ── Ensure base catalog data is present ────────────────────────────────
        $this->call([
            CategorySeeder::class,
            BrandSeeder::class,
            UnitOfMeasureSeeder::class,
            TaxRateSeeder::class,
            HsnCodeSeeder::class,
            AttributeSeeder::class,
        ]);

        // ── Sample products covering all 15 Agri categories ─────────────────
        $examples = [
            [
                'name' => 'Mahyco BG-II Bollgard Cotton Seeds (450g)',
                'sku' => 'SEED-COT-MHY01',
                'category' => 'cotton-seeds',
                'brand' => 'mahyco',
                'hsn' => '1209.99',
                'uom' => 'gram',
                'tax' => 5,
                'price' => 850.00,
                'purchase_price' => 620.00,
                'mrp' => 990.00,
                'stock' => 500,
                'min_stock_level' => 20,
                'status' => 'active',
                'grade' => 'A',
                'barcode' => '8901234567890',
                'weight' => '450 g',
                'batch_tracking' => false,
                'expiry_tracking' => true,
                'allow_overselling' => true,
                'overselling_qty' => 50,
                'description' => 'High-yielding hybrid BG-II cotton seeds with built-in bollworm resistance.',
                'application_instructions' => 'Sow 1 packet per acre in well-drained loamy soil. Row spacing: 90 cm × 60 cm.',
            ],
            [
                'name' => 'Syngenta NK 6240 Maize / Corn Hybrid Seeds (4 kg)',
                'sku' => 'SEED-MAIZE-SYN01',
                'category' => 'maize-corn-seeds',
                'brand' => 'syngenta-seeds',
                'hsn' => '1209.99',
                'uom' => 'kilogram',
                'tax' => 5,
                'price' => 1200.00,
                'purchase_price' => 880.00,
                'mrp' => 1399.00,
                'stock' => 300,
                'min_stock_level' => 15,
                'status' => 'active',
                'grade' => 'A',
                'barcode' => '8901234567891',
                'weight' => '4 kg',
                'batch_tracking' => false,
                'expiry_tracking' => true,
                'allow_overselling' => false,
                'overselling_qty' => 0,
                'description' => 'High-performance yellow flint hybrid maize seed. Suitable for kharif season.',
                'application_instructions' => 'Sow at 4 kg/acre. Spacing 60×25 cm. Germinates in 5–7 days.',
            ],
            [
                'name' => 'IFFCO DAP Fertilizer 50 kg Bag',
                'sku' => 'FERT-DAP-IFFCO50',
                'category' => 'chemical-fertilizers',
                'brand' => 'iffco',
                'hsn' => '3103',
                'uom' => 'bag',
                'tax' => 5,
                'price' => 1350.00,
                'purchase_price' => 1100.00,
                'mrp' => 1450.00,
                'stock' => 400,
                'min_stock_level' => 30,
                'status' => 'active',
                'grade' => 'A',
                'barcode' => '8909111222334',
                'weight' => '50 kg',
                'batch_tracking' => true,
                'expiry_tracking' => false,
                'allow_overselling' => false,
                'overselling_qty' => 0,
                'description' => 'Di-Ammonium Phosphate – 18:46:00. Provides nitrogen and phosphorus for robust root development.',
                'application_instructions' => 'Apply 50 kg/acre as basal dose before sowing. Mix into soil by tilling.',
            ],
            [
                'name' => 'Anandi Organics Vermicompost Manure 25 kg',
                'sku' => 'FERT-VERM-AND25',
                'category' => 'vermicompost',
                'brand' => 'anandi-organics',
                'hsn' => '3101',
                'uom' => 'bag',
                'tax' => 0,
                'price' => 280.00,
                'purchase_price' => 190.00,
                'mrp' => 320.00,
                'stock' => 600,
                'min_stock_level' => 50,
                'status' => 'active',
                'grade' => 'A',
                'barcode' => '8901122445566',
                'weight' => '25 kg',
                'batch_tracking' => false,
                'expiry_tracking' => false,
                'allow_overselling' => true,
                'overselling_qty' => 100,
                'description' => 'NPOP-certified vermicompost produced from red earthworms. Improves soil texture and microbial activity.',
                'application_instructions' => 'Apply 2–4 t/acre. Mix into top 6–8 inches of soil before planting.',
            ],
            [
                'name' => 'UPL Saaf Fungicide (Carbendazim 12% + Mancozeb 63% WP) 1 kg',
                'sku' => 'PROT-FUN-UPL01',
                'category' => 'fungicides',
                'brand' => 'upl',
                'hsn' => '3808.92',
                'uom' => 'kilogram',
                'tax' => 18,
                'price' => 680.00,
                'purchase_price' => 510.00,
                'mrp' => 750.00,
                'stock' => 120,
                'min_stock_level' => 10,
                'status' => 'active',
                'grade' => 'A',
                'barcode' => '8909876543210',
                'weight' => '1 kg',
                'batch_tracking' => true,
                'expiry_tracking' => true,
                'allow_overselling' => false,
                'overselling_qty' => 0,
                'description' => 'Systemic and contact fungicide. Controls powdery mildew, blast, tikka & leaf spot.',
                'application_instructions' => 'Mix 2 g/L of water. Spray at 7–10 day intervals at first sign of infection.',
            ],
            [
                'name' => 'Dhanuka Tata Mida Imidacloprid 17.8% SL Insecticide 500 ml',
                'sku' => 'PROT-INS-DHA01',
                'category' => 'insecticides',
                'brand' => 'dhanuka',
                'hsn' => '3808.91',
                'uom' => 'milliliter',
                'tax' => 18,
                'price' => 380.00,
                'purchase_price' => 280.00,
                'mrp' => 430.00,
                'stock' => 180,
                'min_stock_level' => 12,
                'status' => 'active',
                'grade' => 'A',
                'barcode' => '8905551234567',
                'weight' => '500 ml',
                'batch_tracking' => true,
                'expiry_tracking' => true,
                'allow_overselling' => false,
                'overselling_qty' => 0,
                'description' => 'Systemic insecticide for sucking pest control (aphid, whitefly, jassid, thrips).',
                'application_instructions' => 'Dilute 0.5 ml/L of water. Spray at the base of plants for soil drench.',
            ],
            [
                'name' => 'Aspee Solo Knapsack Manual Sprayer 16 L',
                'sku' => 'TOOL-SPR-ASP16',
                'category' => 'sprayers',
                'brand' => 'aspee-agro',
                'hsn' => '8424',
                'uom' => 'piece',
                'tax' => 18,
                'price' => 890.00,
                'purchase_price' => 640.00,
                'mrp' => 999.00,
                'stock' => 80,
                'min_stock_level' => 5,
                'status' => 'active',
                'grade' => 'B',
                'barcode' => '8901122334499',
                'weight' => '2.1 kg',
                'batch_tracking' => false,
                'expiry_tracking' => false,
                'allow_overselling' => false,
                'overselling_qty' => 0,
                'description' => '16L high-quality knapsack sprayer with brass nozzle. Ideal for field crops and orchards.',
                'application_instructions' => 'Fill tank up to 16L mark. Pump 8–10 strokes to pressurise. Spray uniformly.',
            ],
            [
                'name' => 'Jain Inline Drip Lateral Pipe 16mm × 30cm Spacing 400m Roll',
                'sku' => 'IRRI-DRIP-JN400',
                'category' => 'drip-irrigation',
                'brand' => 'jain-irrigation',
                'hsn' => '3917',
                'uom' => 'roll',
                'tax' => 18,
                'price' => 4200.00,
                'purchase_price' => 3100.00,
                'mrp' => 4800.00,
                'stock' => 45,
                'min_stock_level' => 5,
                'status' => 'active',
                'grade' => 'A',
                'barcode' => '8901122334455',
                'weight' => '15 kg',
                'batch_tracking' => false,
                'expiry_tracking' => false,
                'allow_overselling' => false,
                'overselling_qty' => 0,
                'description' => 'High-durability LLDPE 16mm inline drip lateral pipe at 30 cm emitter spacing. 4 LPH discharge.',
                'application_instructions' => 'Lay along crop rows. Flush line ends weekly. Use filter (150 mesh) at header.',
            ],
            [
                'name' => 'Shakti Pump 1HP Centrifugal Water Pump',
                'sku' => 'IRRI-PUMP-SKT1HP',
                'category' => 'water-pumps',
                'brand' => 'shakti-pumps',
                'hsn' => '8413',
                'uom' => 'piece',
                'tax' => 18,
                'price' => 5800.00,
                'purchase_price' => 4200.00,
                'mrp' => 6500.00,
                'stock' => 25,
                'min_stock_level' => 3,
                'status' => 'active',
                'grade' => 'A',
                'barcode' => '8901234567892',
                'weight' => '8 kg',
                'batch_tracking' => false,
                'expiry_tracking' => false,
                'allow_overselling' => false,
                'overselling_qty' => 0,
                'description' => '1 HP single-phase centrifugal pump with CI impeller and brass port. Max head 30m.',
                'application_instructions' => 'Install on stable platform. Prime pump before start. Use ISI wire & starter.',
            ],
            [
                'name' => 'HDPE Grow Bag 24×24 inch (Pack of 10)',
                'sku' => 'GRWB-HDPE-2424-10',
                'category' => 'grow-bags',
                'brand' => 'generic-unbranded',
                'hsn' => '3926',
                'uom' => 'packet',
                'tax' => 12,
                'price' => 350.00,
                'purchase_price' => 230.00,
                'mrp' => 400.00,
                'stock' => 250,
                'min_stock_level' => 20,
                'status' => 'active',
                'grade' => 'B',
                'barcode' => '8905559876543',
                'weight' => '1.2 kg',
                'batch_tracking' => false,
                'expiry_tracking' => false,
                'allow_overselling' => true,
                'overselling_qty' => 50,
                'description' => 'UV-stabilised 200-micron HDPE grow bags. Ideal for tomato, capsicum, cucumber & herbs.',
                'application_instructions' => 'Fill with 1:1:1 mix of soil, compost & cocopeat. Ensure drainage holes at base.',
            ],
            [
                'name' => 'BioWorks Rhizobium Bio-fertilizer Liquid 1 L',
                'sku' => 'FERT-BIO-RHZ01',
                'category' => 'bio-fertilizers',
                'brand' => 'bioworks',
                'hsn' => '3002',
                'uom' => 'liter',
                'tax' => 5,
                'price' => 180.00,
                'purchase_price' => 120.00,
                'mrp' => 220.00,
                'stock' => 200,
                'min_stock_level' => 15,
                'status' => 'active',
                'grade' => 'A',
                'barcode' => '8901110002233',
                'weight' => '1 L',
                'batch_tracking' => true,
                'expiry_tracking' => true,
                'allow_overselling' => false,
                'overselling_qty' => 0,
                'description' => 'Live Rhizobium culture for pulse & legume crops. Fixes atmospheric nitrogen in root nodules.',
                'application_instructions' => 'Seed treatment: mix 10 ml/kg of seed. Soil application: 1 L/acre diluted in 200L water.',
            ],
            [
                'name' => 'Coromandel Cattle Feed Pellets 50 kg',
                'sku' => 'AFEED-CAT-COR50',
                'category' => 'cattle-feed',
                'brand' => 'coromandel',
                'hsn' => '2309',
                'uom' => 'bag',
                'tax' => 0,
                'price' => 1200.00,
                'purchase_price' => 950.00,
                'mrp' => 1350.00,
                'stock' => 150,
                'min_stock_level' => 20,
                'status' => 'active',
                'grade' => 'B',
                'barcode' => '8909988776655',
                'weight' => '50 kg',
                'batch_tracking' => true,
                'expiry_tracking' => true,
                'allow_overselling' => false,
                'overselling_qty' => 0,
                'description' => 'Balanced pellet feed for crossbred & HF dairy cattle. 22% CP, 70% TDN.',
                'application_instructions' => 'Feed 3–4 kg/day per adult animal. Provide fresh water continuously.',
            ],
            [
                'name' => 'PP Woven Gunny Bag 50 kg Capacity (Pack of 50)',
                'sku' => 'STOR-GUN-PP50-50',
                'category' => 'gunny-bags-sacks',
                'brand' => 'generic-unbranded',
                'hsn' => '6305',
                'uom' => 'packet',
                'tax' => 5,
                'price' => 750.00,
                'purchase_price' => 550.00,
                'mrp' => 850.00,
                'stock' => 100,
                'min_stock_level' => 10,
                'status' => 'active',
                'grade' => 'B',
                'barcode' => '8901234501234',
                'weight' => '4 kg',
                'batch_tracking' => false,
                'expiry_tracking' => false,
                'allow_overselling' => true,
                'overselling_qty' => 20,
                'description' => 'Virgin PP woven sacks for grain, fertiliser and seed storage. UV treated. 50 kg load capacity.',
                'application_instructions' => 'Store in cool dry place. Do not stack more than 12 bags high.',
            ],
            [
                'name' => 'Farmer Safety PPE Kit (Full Body – Apron, Gloves, Goggles, Mask)',
                'sku' => 'SAFE-PPE-FULL01',
                'category' => 'safety-ppe-kits',
                'brand' => 'generic-unbranded',
                'hsn' => '6210',
                'uom' => 'set',
                'tax' => 12,
                'price' => 550.00,
                'purchase_price' => 370.00,
                'mrp' => 650.00,
                'stock' => 60,
                'min_stock_level' => 5,
                'status' => 'active',
                'grade' => 'B',
                'barcode' => '8901234509999',
                'weight' => '600 g',
                'batch_tracking' => false,
                'expiry_tracking' => false,
                'allow_overselling' => false,
                'overselling_qty' => 0,
                'description' => 'Complete personal protective equipment set for safe pesticide / chemical handling.',
                'application_instructions' => 'Always wear complete PPE before mixing or spraying agrochemicals.',
            ],
            [
                'name' => 'Soil Testing Kit – NPK & pH (Field Use)',
                'sku' => 'SOIL-TEST-NPK-01',
                'category' => 'soil-testing-kits',
                'brand' => 'generic-unbranded',
                'hsn' => '3822',
                'uom' => 'piece',
                'tax' => 18,
                'price' => 1800.00,
                'purchase_price' => 1300.00,
                'mrp' => 2100.00,
                'stock' => 40,
                'min_stock_level' => 3,
                'status' => 'active',
                'grade' => 'A',
                'barcode' => '8901234502345',
                'weight' => '800 g',
                'batch_tracking' => false,
                'expiry_tracking' => true,
                'allow_overselling' => false,
                'overselling_qty' => 0,
                'description' => 'Field soil testing kit with reagents to measure N, P, K levels and soil pH. 200 tests per kit.',
                'application_instructions' => 'Collect soil sample 6" deep. Mix with reagent as per instruction booklet. Compare with colour chart.',
            ],
        ];

        $warehouse = Warehouse::first();
        $supplier = Supplier::inRandomOrder()->first();

        foreach ($examples as $example) {
            $category = Category::where('slug', $example['category'])->first();
            $brand = Brand::where('slug', $example['brand'])->first();
            $uom = UnitOfMeasure::where('slug', $example['uom'])->first();
            $taxRate = TaxRate::where('rate', $example['tax'])->first();
            $hsn = HsnCode::where('code', $example['hsn'])->first();

            $product = Product::firstOrCreate(
                ['sku' => $example['sku']],
                [
                    'name' => $example['name'],
                    'slug' => Str::slug($example['name']),
                    'category_id' => $category?->id,
                    'brand_id' => $brand?->id,
                    'tax_rate_id' => $taxRate?->id,
                    'hsn_code_id' => $hsn?->id,
                    'uom_id' => $uom?->id,
                    'default_warehouse_id' => $warehouse?->id,
                    'supplier_id' => $supplier?->id,
                    'purchase_price' => $example['purchase_price'],
                    'mrp' => $example['mrp'],
                    'selling_price' => $example['price'],
                    'min_stock_level' => $example['min_stock_level'] ?? 10,
                    'allow_overselling' => true,
                    'overselling_qty' => 10,
                    'batch_tracking' => $example['batch_tracking'],
                    'expiry_tracking' => $example['expiry_tracking'],
                    'manage_stock' => true,
                    'is_sku_enabled' => true,
                    'status' => $example['status'],
                    'is_active' => $example['status'] === 'active',
                    'description' => $example['description'],
                    'application_instructions' => $example['application_instructions'] ?? null,
                    'grade' => $example['grade'],
                    'barcode' => $example['barcode'] ?? null,
                    'weight' => $example['weight'] ?? null,
                    'image_path' => null,
                    'default_discount' => 0,
                    'default_discount_type' => 'percent',
                ],
            );

            if ($product->default_warehouse_id && class_exists(InventoryService::class)) {
                try {
                    app(InventoryService::class)->setStock(
                        $product->id,
                        $product->default_warehouse_id,
                        10
                    );
                } catch (\Exception $e) {
                    // Fail silently if service requirements differ in runtime environments
                }
            }
        }
    }
}
